//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewWordProject.BrurayAndDVD._01
{


    public partial class BrurayAndDVD_TVアニメ_新しいセカイプロジェクト_公式サイト
    {

        /// <summary>
        /// form1 control.
        /// </summary>
    }
}
